// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputLink struct {
	FromID int `json:"from_id"`
	ToID   int `json:"to_id"`
}

type Link struct {
	ID     int `json:"id"`
	FromID int `json:"from_id"`
	ToID   int `json:"to_id"`
}
