// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Big struct {
	Data []string `json:"data"`
}

type BigInput struct {
	Data []string `json:"data"`
}

type Small struct {
	Data int `json:"data"`
}

type SmallInput struct {
	Data int `json:"data"`
}
